### ISSUE TITLE
Durable functions won't run

### ISSUE THREAD

**Issue by Arash-Sabet** [merken/local-azure-functions#1]
Great article and repo! Very useful for me and thanks for sharing it. I followed the pattern in your code but failed to make durable functions work. Just wondering, have you had a successful conclusion in this context? 

Please feel free to have a look at[ this issue that I opened.](https://github.com/Azure/azure-functions-durable-extension/issues/1720)

**Comment by merken** [comment]
Hi Arash, Sorry to hear but I've not tested this with Durable Functions, I'll be watching your issue closely...

**Comment by Arash-Sabet** [comment]
@merken I got the durable functions working. The issue was related to the environment variables misconfiguration that I fixed.
